from datetime import datetime

class User:
    def __init__(self, name, email, phone, department, designation, profilePhoto, employeeId, password):
        self.id = None  # This will be generated by Supabase
        self.name = name
        self.email = email
        self.phone = phone
        self.department = department
        self.designation = designation
        self.profilePhoto = profilePhoto
        self.password = password
        self.employeeId = employeeId
        self.created_at = datetime.utcnow()

    def __repr__(self):
        return f"<User  {self.email}>"

    @staticmethod
    def from_dict(data):
        """Create a User instance from a dictionary."""
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            department=data['department'],
            designation=data['designation'],
            profilePhoto=data['profilePhoto'],
            password=data['password'],
            employeeId=data['employeeId']
        )
        user.id = data.get('id')  # Get the ID if it exists
        user.created_at = data.get('created_at', datetime.utcnow())
        return user

    @staticmethod
    def create(supabase_client, name, email, phone, department, designation, profilePhoto, employeeId, password):
        """Create a new user in Supabase."""
        new_user = User(
            name=name,
            email=email,
            phone=phone,
            department=department,
            designation=designation,
            profilePhoto=profilePhoto,
            password=password,
            employeeId=employeeId
        )

        # Hash the password before inserting (make sure to import Bcrypt)
        from flask_bcrypt import Bcrypt
        bcrypt = Bcrypt()
        hashed_password = bcrypt.generate_password_hash(new_user.password).decode('utf-8')

        # Insert the user into Supabase
        response = supabase_client.table('users').insert({
            'name': new_user.name,
            'email': new_user.email,
            'phone': new_user.phone,
            'department': new_user.department,
            'designation': new_user.designation,
            'profilePhoto': new_user.profilePhoto,
            'password': hashed_password, 
            'employeeId': employeeId,
            'created_at': new_user.created_at
        }).execute()

        if response.status_code == 201:
            return User.from_dict(response.data[0])  # Return the created user
        else:
            raise Exception(f"Error creating user: {response.json()}")